export const teamThemes = {
  // Premier League
  1: {
    name: "Arsenal",
    primary: "#EF0107",
    accent: "#023474",
    text: "#FFFFFF",
  },
  2: {
    name: "Aston Villa",
    primary: "#95BFE5",
    accent: "#670E36",
    text: "#FFFFFF",
  },
  3: {
    name: "Bournemouth",
    primary: "#DA291C",
    accent: "#000000",
    text: "#FFFFFF",
  },
  4: {
    name: "Brentford",
    primary: "#E30613",
    accent: "#FFFFFF",
    text: "#000000",
  },
  5: {
    name: "Brighton and Hove Albion",
    primary: "#0057B8",
    accent: "#FFFFFF",
    text: "#000000",
  },
  6: {
    name: "Chelsea",
    primary: "#034694",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },
  7: {
    name: "Crystal Palace",
    primary: "#1B458F",
    accent: "#A7A5A6",
    text: "#FFFFFF",
  },
  8: {
    name: "Everton",
    primary: "#003399",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },
  9: { name: "Fulham", primary: "#000000", accent: "#FFFFFF", text: "#FFFFFF" },
  10: {
    name: "Ipswich Town",
    primary: "#0057B8",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },
  11: {
    name: "Leicester City",
    primary: "#003090",
    accent: "#FDBE11",
    text: "#FFFFFF",
  },
  12: {
    name: "Liverpool",
    primary: "#C8102E",
    accent: "#00B2A9",
    text: "#FFFFFF",
  },
  13: {
    name: "Manchester City",
    primary: "#6CABDD",
    accent: "#1C2C5B",
    text: "#000000",
  },
  14: {
    name: "Manchester United",
    primary: "#DA291C",
    accent: "#FBE122",
    text: "#FFFFFF",
  },
  15: {
    name: "Newcastle United",
    primary: "#241F20",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },
  16: {
    name: "Nottingham Forest",
    primary: "#E53233",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },
  17: {
    name: "Southampton",
    primary: "#D71920",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },
  18: {
    name: "Tottenham Hotspur",
    primary: "#132257",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },
  19: {
    name: "West Ham United",
    primary: "#7A263A",
    accent: "#1BB1E7",
    text: "#FFFFFF",
  },
  20: {
    name: "Wolverhampton Wanderers",
    primary: "#FDB913",
    accent: "#231F20",
    text: "#000000",
  },

  // La Liga
  21: {
    name: "Real Madrid",
    primary: "#FEBE10",
    accent: "#00529F",
    text: "#000000",
  },
  22: {
    name: "Barcelona",
    primary: "#004D98",
    accent: "#A50044",
    text: "#FFFFFF",
  },
  23: {
    name: "Atletico Madrid",
    primary: "#C8102E",
    accent: "#012169",
    text: "#FFFFFF",
  },
  24: {
    name: "Athletic Bilbao",
    primary: "#EE1A3D",
    accent: "#FFFFFF",
    text: "#000000",
  },
  25: {
    name: "Real Betis",
    primary: "#0B9952",
    accent: "#FFFFFF",
    text: "#000000",
  },
  26: {
    name: "Sevilla",
    primary: "#FFFFFF",
    accent: "#D00027",
    text: "#000000",
  },
  27: {
    name: "Real Sociedad",
    primary: "#005BAA",
    accent: "#FFFFFF",
    text: "#000000",
  },
  28: {
    name: "Valencia",
    primary: "#F18E00",
    accent: "#000000",
    text: "#FFFFFF",
  },
  29: {
    name: "Getafe",
    primary: "#003DA5",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },
  30: {
    name: "Rayo Vallecano",
    primary: "#FFFFFF",
    accent: "#D6001C",
    text: "#000000",
  },
  31: {
    name: "Villarreal",
    primary: "#FFF200",
    accent: "#000000",
    text: "#000000",
  },
  32: {
    name: "Girona",
    primary: "#DA291C",
    accent: "#FFFFFF",
    text: "#000000",
  },
  33: {
    name: "Osasuna",
    primary: "#D6001C",
    accent: "#002B5C",
    text: "#FFFFFF",
  },
  34: {
    name: "Celta Vigo",
    primary: "#A1C9F1",
    accent: "#DA291C",
    text: "#000000",
  },
  35: {
    name: "Mallorca",
    primary: "#DA291C",
    accent: "#000000",
    text: "#FFFFFF",
  },
  36: {
    name: "Espanyol",
    primary: "#005BAA",
    accent: "#FFFFFF",
    text: "#000000",
  },
  37: {
    name: "Alavés",
    primary: "#005BAA",
    accent: "#FFFFFF",
    text: "#000000",
  },
  38: {
    name: "Real Valladolid",
    primary: "#5B2A83",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },
  39: {
    name: "Las Palmas",
    primary: "#FFD700",
    accent: "#0000CD",
    text: "#000000",
  },
  40: {
    name: "Leganes",
    primary: "#0072CE",
    accent: "#FFFFFF",
    text: "#000000",
  },

  // Serie A
  41: {
    name: "Atalanta",
    primary: "#1C1C1C",
    accent: "#0055A4",
    text: "#FFFFFF",
  },
  42: {
    name: "Bologna",
    primary: "#D00027",
    accent: "#002B5C",
    text: "#FFFFFF",
  },
  43: {
    name: "Cagliari",
    primary: "#D00027",
    accent: "#002B5C",
    text: "#FFFFFF",
  },
  44: { name: "Como", primary: "#005BAC", accent: "#FFFFFF", text: "#FFFFFF" },
  45: {
    name: "Empoli",
    primary: "#005BAC",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },
  46: {
    name: "Fiorentina",
    primary: "#4C1F8C",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },
  47: { name: "Genoa", primary: "#D00027", accent: "#002B5C", text: "#FFFFFF" },
  48: { name: "Inter", primary: "#005BAC", accent: "#FFFFFF", text: "#FFFFFF" },
  49: {
    name: "Juventus",
    primary: "#000000",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },
  50: { name: "Lazio", primary: "#A8D4F0", accent: "#FFFFFF", text: "#000000" },
  51: { name: "Lecce", primary: "#FEDD00", accent: "#D00027", text: "#000000" },
  52: {
    name: "AC Milan",
    primary: "#FB090B",
    accent: "#000000",
    text: "#FFFFFF",
  },
  53: { name: "Monza", primary: "#ED1C24", accent: "#FFFFFF", text: "#FFFFFF" },
  54: {
    name: "Napoli",
    primary: "#0074B7",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },
  55: { name: "Parma", primary: "#FEDD00", accent: "#231F20", text: "#000000" },
  56: { name: "Roma", primary: "#8E1C1A", accent: "#FDB913", text: "#FFFFFF" },
  57: {
    name: "Torino",
    primary: "#781F1E",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },
  58: {
    name: "Udinese",
    primary: "#000000",
    accent: "#D9D9D6",
    text: "#FFFFFF",
  },
  59: {
    name: "Venezia",
    primary: "#000000",
    accent: "#FF7F00",
    text: "#FFFFFF",
  },
  60: {
    name: "Verona",
    primary: "#00285E",
    accent: "#F7D117",
    text: "#FFFFFF",
  },

  // Bundesliga
  61: {
    name: "1. FC Köln",
    primary: "#E30613",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },
  62: {
    name: "1899 Hoffenheim",
    primary: "#005CA9",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },
  63: {
    name: "Bayer Leverkusen",
    primary: "#E32219",
    accent: "#000000",
    text: "#FFFFFF",
  },
  64: {
    name: "Bayern Munich",
    primary: "#DC052D",
    accent: "#0066B2",
    text: "#FFFFFF",
  },
  65: {
    name: "Borussia Dortmund",
    primary: "#FDE100",
    accent: "#000000",
    text: "#000000",
  },
  66: {
    name: "Borussia Mönchengladbach",
    primary: "#000000",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },
  67: {
    name: "Eintracht Frankfurt",
    primary: "#E30613",
    accent: "#000000",
    text: "#FFFFFF",
  },
  68: {
    name: "FC Augsburg",
    primary: "#006A44",
    accent: "#DD1C1A",
    text: "#FFFFFF",
  },
  69: {
    name: "Hamburger SV",
    primary: "#0F53B0",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },
  70: {
    name: "Hannover 96",
    primary: "#006633",
    accent: "#000000",
    text: "#FFFFFF",
  },
  71: {
    name: "Hertha BSC",
    primary: "#004C9B",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },
  72: {
    name: "Mainz 05",
    primary: "#C60C30",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },
  73: {
    name: "RB Leipzig",
    primary: "#E20E0E",
    accent: "#000000",
    text: "#FFFFFF",
  },
  74: {
    name: "SC Freiburg",
    primary: "#000000",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },
  75: {
    name: "Schalke 04",
    primary: "#0070B8",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },
  76: {
    name: "VfB Stuttgart",
    primary: "#E30613",
    accent: "#FFFFFF",
    text: "#000000",
  },
  77: {
    name: "VfL Wolfsburg",
    primary: "#65B32E",
    accent: "#FFFFFF",
    text: "#000000",
  },
  78: {
    name: "Werder Bremen",
    primary: "#008557",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },

  // Ligue 1
  79: {
    name: "AS Monaco",
    primary: "#DA1A32",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },
  80: {
    name: "Angers",
    primary: "#000000",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },
  81: {
    name: "Bordeaux",
    primary: "#001C3D",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },
  82: { name: "Caen", primary: "#002E5F", accent: "#C8102E", text: "#FFFFFF" },
  83: {
    name: "Dijon FCO",
    primary: "#C8102E",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },
  84: {
    name: "Guingamp",
    primary: "#D71920",
    accent: "#000000",
    text: "#FFFFFF",
  },
  85: { name: "Lille", primary: "#ED1B24", accent: "#00245D", text: "#FFFFFF" },
  86: { name: "Lyon", primary: "#001A57", accent: "#DA291C", text: "#FFFFFF" },
  87: {
    name: "Marseille",
    primary: "#009DDC",
    accent: "#FFFFFF",
    text: "#000000",
  },
  88: { name: "Metz", primary: "#912F2F", accent: "#FFFFFF", text: "#FFFFFF" },
  89: {
    name: "Montpellier",
    primary: "#F77F00",
    accent: "#003566",
    text: "#FFFFFF",
  },
  90: {
    name: "Nantes",
    primary: "#FFE100",
    accent: "#008751",
    text: "#000000",
  },
  91: { name: "Nice", primary: "#DA291C", accent: "#000000", text: "#FFFFFF" },
  92: {
    name: "Paris Saint-Germain",
    primary: "#004170",
    accent: "#DA1921",
    text: "#FFFFFF",
  },
  93: {
    name: "SC Amiens",
    primary: "#DADADA",
    accent: "#000000",
    text: "#000000",
  },
  94: {
    name: "Saint-Etienne",
    primary: "#008A4F",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },
  95: {
    name: "Stade Rennes",
    primary: "#E30613",
    accent: "#000000",
    text: "#FFFFFF",
  },
  96: {
    name: "Strasbourg",
    primary: "#0055A4",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },
  97: {
    name: "Toulouse",
    primary: "#512D6D",
    accent: "#FFFFFF",
    text: "#FFFFFF",
  },
  98: {
    name: "Troyes",
    primary: "#005BAC",
    accent: "#FFD700",
    text: "#FFFFFF",
  },
};
